### ISSUE TITLE
JedisPipeline missing zadd with multi members Map<String, Double>

### ISSUE THREAD

**Issue by maksimlikharev** [Netflix/dyno#107]
this defined in PipelineBase, but no accessor in JedisPipeline

  public Response<Long> zadd(String key, Map<String, Double> scoreMembers) {
    getClient(key).zadd(key, scoreMembers);
    return getResponse(BuilderFactory.LONG);
  }

**Comment by ipapapa** [comment]
Thank you for reporting this. 

Dyno currently uses Jedis 2.7.3 as shown in the [build.gradle](https://github.com/Netflix/dyno/blob/master/build.gradle#L78). 

[RedisPipeline](https://github.com/xetorthio/jedis/blob/2.7/src/main/java/redis/clients/jedis/RedisPipeline.java#L139) from Jedis has not implemented the ZADD with Map for the score members. It was added in Jedis >2.8. 

Moving to 2.8 requires several changes and most of our use cases at Netflix do not need those extra APIs. Nonetheless, it is something we will try to spend some cycles in the near future, or interested folks from the open source can contribute on this.

**Comment by ipapapa** [comment]
We have recently moved to Jedis 2.8: https://github.com/Netflix/dyno/commit/b195bd2fcaa753cbbbc071281622db19418ee166
