### ISSUE TITLE
Support for MULTI - EXEC

### ISSUE THREAD

**Issue by vvapp** [Netflix/dyno#131]
Hi,

I am looking to port my existing jedis api calls to dyno jedis client. I have to execute transactions and was looking to see if the MULTI-EXEC feature is supported in the dyno client. I couldn't find this support. Can you please let me know how to achieve MULTI-EXEC commands using dyno client code?

Thanks,
Vasavi

**Comment by ipapapa** [comment]
@vvapp Dynomite does not support MULTI-EXEC, hence there was no reason to integrate them Dyno. It would not make sense to support transactions in system that is designed for high availability and partition tolerance. For more information about the Redis operations that are supported check out the [notes](https://github.com/Netflix/dynomite/blob/dev/notes/redis.md).

**Comment by vvapp** [comment]
Thanks for the information. Appreciate your quick response.
