### ISSUE TITLE
Switching between multiple databases using Jedis client

### ISSUE THREAD

**Issue by vvapp** [Netflix/dyno#135]
Hi,

We have multiple databases in our redis instance. I did not see support for SELECT index in dynomite. Can you please confirm if creating and using multiple redis databases are supported by dynomite?

Thanks,
Vasavi

**Comment by ipapapa** [comment]
Hello @vvapp you can extend Dynomite to connect to multiple Redis databases. However, the way were are using it is with a single Dynomite/Redis per instance, so this is what is implemented by default. Other than contributing to the software itself, there are several other alternative designs you can have like running separate pairs of Dynomite/Redis per database.

**Comment by vvapp** [comment]
Thanks! We will evaluate the options. Appreciate your response.
