### ISSUE TITLE
Dual writes to support the failure recovery in writing to the secondary cluster

### ISSUE THREAD

**Issue by timiblossom** [Netflix/dyno#136]
Currently, all writes (we can ignore the reads) to the new cluster in Dual writes are fire and forget.  This would case some data loss in moving data in some cases.  There are couple of options to do this: 
    1. Storing failure requests somewhere and retry later
    2. Fail the operations so that the application layer can retry  
    3. Guarantee the writes always successful (which is hard)

**Comment by ipapapa** [comment]
1. We can retry a failure request later as the key may have expired and if the key comes with a TTL then the TTL will be set incorrectly.
3. This is hard and it may decrease the performance output that we may want to measure in shadow mode.

2. Failing the application and retry is relatively easy to do, and it may make sense to have a configuration parameter for this if the client chooses to not swallow failed requests by the dual writer pool.

**Comment by ipapapa** [comment]
Have moved the notes under `Projects`. No need to keep this issue open.
