### ISSUE TITLE
maven published artifacts have pom.xml depencies marked with `runtime` scope instead of `compile`.

### ISSUE THREAD

**Issue by anguenot** [Netflix/dyno#138]
Hey, 

This issue makes the use of the Dyno libs, and other Netflix libs, very painful for the rest of us using maven because we have to exclude all the transitive dependencies of the Netflix libs and define (and maintain) custom dependency management overrides.

Last version of the Dyno libs without broken maven artifacts is 1.0.6 (2015/01/22):

For instance, dyno-core:

  http://search.maven.org/#artifactdetails%7Ccom.netflix.dyno%7Cdyno-core%7C1.0.6%7Cjar

Latest Dyno libs in comparison with the broken `compile` scopes:

  http://search.maven.org/#artifactdetails%7Ccom.netflix.dyno%7Cdyno-core%7C1.5.0%7Cjar

I see that people been reporting the issue on Netflix Archaius:

   https://github.com/Netflix/archaius/issues/379

Any update for the Dyno libs?

Thanks. 

   J.

**Comment by ipapapa** [comment]
Hello @anguenot I am sorry for my late response. Wouldn't adding `nebula.compile-api` in build.gradle work for you? See this https://github.com/nebula-plugins/nebula-publishing-plugin/issues/31 for more information.

**Comment by anguenot** [comment]
Hey @ipapapa, 

Thank you for your answer. 

You mean adding that plugin, as a workaround, in the `Dyno` `build.gradle` itself and republish the artifacts on the maven central or you suggesting I deal with the problem that way on my side?

   J.

**Comment by ipapapa** [comment]
@anguenot I was wondering if adding it in the `build.gradle` would work, and I can potentially republish the latest artifact.

**Comment by anguenot** [comment]
@ipapapa  reading all the bug reports it seems to be the preferred workaround to that issue. Do you want me to spend some time trying to add it and  publish locally to see of the scope are getting fixed first?

**Comment by ipapapa** [comment]
@anguenot yes that would help a lot; feel free to file a PR with the change.

**Comment by anguenot** [comment]
@ipapapa  just submitted a PR for a workaround fixing the generated maven artifacts pom.xml files. Tested the resulting artifacts locally and all seems fine on my end.

**Comment by ipapapa** [comment]
@anguenot I Am little missing why we need to the workaround instead of just: https://github.com/nebula-plugins/nebula-publishing-plugin#nebulacompile-api

**Comment by anguenot** [comment]
@ipapapa  reading the actual doc for this plugin:

> Note that nebula.maven-dependencies is based on the Gradle maven-publish plugin, which places first order compile dependencies in the runtime scope in the POM. If you wish your compile dependencies to be compile scope dependencies in the POM, you can add a withXml block like so:
> 
> publishing {
>     publications {
>         nebula(MavenPublication) {
>             pom.withXml {
>                 configurations.compile.resolvedConfiguration.firstLevelModuleDependencies.each { dep ->
>                     asNode().dependencies[0].dependency.find {
>                         it.artifactId[0].text() == dep.moduleName &&
>                         it.groupId[0].text() == dep.moduleGroup
>                     }?.scope[0]?.value = 'compile'
>                 }
>             }
>         }
>     }
> }

The plugin does not seem to be doing the job just like that unless I missed something.

**Comment by anguenot** [comment]
@ipapapa  ok so I just tested using just that plugin and it seems it will only do the job (fixing the wrong 'runtime' scopes to correct 'compile')  if we  change  'compile' scopes on Gradle dependencies as 'compileApi'. 

See below for diff testing a fix against  the 'com.googlecode.json-simple'  compile dependency.

```
diff --git a/build.gradle b/build.gradle
index 90db1f5..12d8361 100644
--- a/build.gradle
+++ b/build.gradle
@@ -13,7 +13,8 @@ subprojects {
     apply plugin: 'nebula.netflixoss'
     apply plugin: 'java'
     apply plugin: 'idea'
-    apply plugin: 'eclipse'    
+    apply plugin: 'eclipse'
+    apply plugin: 'nebula.compile-api'
 
     sourceCompatibility = 1.7
     targetCompatibility = 1.7
@@ -27,7 +28,7 @@ subprojects {
         compile "joda-time:joda-time:2.3"
         compile "org.slf4j:slf4j-api:1.7.6"
         compile "org.slf4j:slf4j-log4j12:1.7.21"
-        compile "com.googlecode.json-simple:json-simple:1.1"
+        compileApi "com.googlecode.json-simple:json-simple:1.1"
         compile "org.apache.httpcomponents:httpclient:4.2.1"
         compile "com.sun.jersey:jersey-core:1.11"
         testCompile "junit:junit:4.11"
 
```

It means we would have to switch all 'compile' to 'compileApi' scopes.

What would like to do? Initial workaround in #139 or that approach with the nebula-compile-api and 'compileApi' scope updates?

**Comment by anguenot** [comment]
Been checking other Netflix projects and it seems the 'compileApi' is in use in a lot of the projects.

Went ahead and opened another PR (#141) for this using the nebula-compile-api plugin.

Will let you decide which one you would rather merged in.

Both of them address the scopes in generated pom files.

**Comment by ipapapa** [comment]
@anguenot thank you very much, I have notified @rspieldenner to get his expert opinion one which approach to follow.

**Comment by ipapapa** [comment]
@anguenot let me know which path you prefer to move forward. It seems that based on Rob's feedback either #139 or #141 need to be updated; however, #141 seems to be a better approach. Please feel free to comment directly on #141 so that we can have a discussion on the best approach to follow.

**Comment by anguenot** [comment]
@ipapapa  IMHO we should go with #139, the workaround, since the gradle behavior of transforming scopes defined as 'compile' to 'runtime' from gradle to maven artifacts is  simply buggy. 

At the end, all the 'compile' scopes defined on the actual Ggadle dependencies must end up as well being defined with 'compile' scope in the maven artifacts dependencies in pom.xml.

It is pretty clear a regression occurred at the gradle level when you compare:

that version, back in 2015, properly defining the compile scopes in the maven artifacts:

   http://search.maven.org/#artifactdetails%7Ccom.netflix.dyno%7Cdyno-core%7C1.0.6%7Cjar

and the latest version carrying 'runtime' dependencies instead of 'compile's:

   http://search.maven.org/#artifactdetails%7Ccom.netfliex.dyno%7Cdyno-core%7C1.5.0%7Cjar

IMHO, a proper fix should be done gradle side.

I understand  @rspieldenner  take on the  'compileApi' usage in #141  as 'nebula.compile-api'  is aimed at addressing another need. Though, I disagree with the personal remarks about maven: gradle and maven have different paradigms and maven does require 'compile' scopes in cases like that.

My take on this is: maven artifacts with the 'runtime' dependencies in pom.xml, as it is right now, will be a major show stopper for Dyno adoption from users (maven currently being used more than gradle).

**Comment by ipapapa** [comment]
Please feel free to close the issue, if everything is OK with you.

**Comment by anguenot** [comment]
Thanks a lot @ipapapa . Will confirm all is fine when the new artifacts will be published on central.

**Comment by anguenot** [comment]
@ipapapa the latest published artifacts (v1.5.1) are working great in maven based projects.  Thank you for merging that PR in.

Will be working on that one now: https://github.com/Netflix/dyno/issues/142 trying to get rid of the AWS dependencies for the rest of us not deploying against AWS.

**Comment by cdancy** [comment]
Believe this approach is no longer required with latest version of gradle if I'm not mistaken.

**Comment by ipapapa** [comment]
Please feel free to create a PR to remove the redundant approach,

**Comment by cdancy** [comment]
@ipapapa sent in a PR. I don't actually use this library ( :) ) just came to this thread due to the issue being mentioned and me applying the solution to the `bitbucket-rest` library I maintain. In either event just wanted to help the broader community and hope the solution works for you guys.
