### ISSUE TITLE
Support for Redis commands across nodes.

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dyno#145]
Hi,

Is there a plan to support Redis commands that gets data across nodes in the same rack? Commands like SUNION, MGET, SINTER etc.

**Comment by ipapapa** [comment]
We do not have currently an internal use case for these commands. We may though add them some time in the near future. If these are a priority for you please feel free to file PR.

**Comment by balajivenki** [comment]
Thanks for the update @ipapapa

**Comment by balajivenki** [comment]
@ipapapa I have finished the implementation for sunion and sinter commands and a PR is been created

https://github.com/Netflix/dyno/pull/147

Can you please review it and merge it. Also if its not too much trouble can you please have it available as maven artifact like 1.5.2 or something. 

Much appreciated.
