### ISSUE TITLE
Make v1.5.7 available in Maven Repository

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dyno#164]
Can you please make v1.5.7 available in Maven Repository.

**Comment by ipapapa** [comment]
Can you remind my what we used to do to make it available in Maven Repository?

**Comment by balajivenki** [comment]
@ipapapa  Unfortunately I couldnt find the issue where you have earlier pushed a release to maven. I think you are looking for this

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

However I am blocked on the issue 

https://github.com/Netflix/dyno/issues/156

can you please take a look at it and I shall take the new version with the fix for issue 156. Please.

**Comment by balajivenki** [comment]
@ipapapa It looks like it is already uploaded into maven repository

https://mvnrepository.com/artifact/com.netflix.dyno/dyno-core

I do see v1.5.7 available and it was uploaded on 23rd Jan 2017. I am marking this as closed. Can you please help us with #156

**Comment by ipapapa** [comment]
Yes, it was also in Jcenter: https://jcenter.bintray.com/com/netflix/dyno/dyno-jedis/1.5.7/ Thanks for confirming
