### ISSUE TITLE
Hash Tag Support

### ISSUE THREAD

**Issue by pcting** [Netflix/dyno#175]
It'll be nice to add in hash tag aware support:
https://github.com/Netflix/dynomite/blob/e5fc3ef856e1ff70050b72313576d81338bfa03c/notes/recommendation.md#hash-tags

**Comment by ipapapa** [comment]
Yes, that would be something interesting to add. Effectively bypass hashing the full key but whatever is in the hashtag. Probably the hashtag can be defined in a FP.

**Comment by ipapapa** [comment]
Some effort has been started: https://github.com/Netflix/dyno/pull/186 Feedback is welcome.

**Comment by ipapapa** [comment]
#186 has been tested and works properly. There have been a few RC releases that already have it. It is in the final reviewing cycles so we can safely close this.
