### ISSUE TITLE
Detecting the RACK failure

### ISSUE THREAD

**Issue by thakurajayL** [Netflix/dyno#204]
HI,
I am trying to understand how dyno client works. Does it take care of doing the health check of all the racks and all the datatacentres. Assume that we have A1,B1,C1 as three dynomite nodes running on RACK1. A2,B2,C2 dynomite nodes running on RACK2.  Wondering what happens if one of the dynomite node A1 crashes on RACK1.  Now from the dyno client perspective, will it talk to B1,C1 & A2 ?  Or will dyno client shift all the traffic to A2,B2,C2 ?

Thanks
Ajay

**Comment by nginxsantos** [comment]
I am also trying to understand how this works in a Topology aware client like (Dyno). Does the client switch to the other RACK when any node in a RACK fails?

I will wait for the notes from the experts.

thanks. santos

**Comment by ipapapa** [comment]
Dyno open connections to all Dynomite nodes. Assuming that A1 and A2 hold the same token range (hence they have replicas of the data), then when A1 fails (and B1 and C1 are healthy( then Dyno will switch to A2. It does not switch B1 and C1 since there is no reason as both replicas of this token range are healthy.

**Comment by thakurajayL** [comment]
Thanks @ipapapa 
If Dyno does not find any replica for A1 then it will declare whole database as down ? Or it continues to serve other available data ? 

Does dyno client supports dual write ?

Thanks Again for your prompt reply.

**Comment by ipapapa** [comment]
We usually deploy 3 replicas A1, A2, and A3. It does not declare the whole database down. If it cannot find a replica, it will provide a client Exception for the operation on the key that belongs to an unavailable token range. It is up to the client to handle the exception they way it wants to. 

Yes, it has a dual writer.

**Comment by ipapapa** [comment]
This question has been inactive for some time. I assume it has been answered and I am closing it.  Please feel free to open a new issue and tag this one if you want to follow up.
