### ISSUE TITLE
DynoJedisClient does not support blocking calls for queue operations

### ISSUE THREAD

**Issue by bshevade** [Netflix/dyno#225]
Hello,

We are using dynomite jedis client (dyno-jedis version 1.6.3) with redis but without the dynomite server at the moment. However, we see that the blocking calls like brpoplpush are not yet supported. Any idea when they will be supported? Thanks!

**Comment by ipapapa** [comment]
We have not added operations that are not supported by Dynomite. This is because we use Dyno with Dynomite. If you find value in adding these operations because you use Dyno in another way, please feel free to fire a PR.

**Comment by ipapapa** [comment]
This question has not moved forward for some time. I am closing this issue assuming it has been answered. Feel free to open a new one if you have any further questions.
