### ISSUE TITLE
Failover case not working : not reading data from replica rack

### ISSUE THREAD

**Issue by PraharshSri** [Netflix/dyno#231]
I have set up two racks each with one server in a data center. Then I have setup dyno client along with dynomite to handle failovers. Now when both redis instances are active then it works fine for read and write both and it has keys in both instances (i.e replica is created) but when I stop one instance of redis on my local and then test again then it doesn't read from the replica which exists on the active instance instead I get the following exception: **com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: rack-1, datacenter: dc, status: Up, hashtag=null], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Datastore refused connection**
Can you please suggest a solution to this?

**Comment by ankur-aggarwal** [comment]
@PraharshSri I am seeing this issue. Did you find a fix for this?

**Comment by srirama-rayaprolu** [comment]
I am also getting the same issue, does there configurations changes required for this to work?

**Comment by abhinav0101** [comment]
anyone there to help ? How did you solve it ?
