### ISSUE TITLE
Double Decrmment api is not available

### ISSUE THREAD

**Issue by duraisridhar** [Netflix/dyno#236]
Hi,

DynoJedisClient have incrByFloat supporting the incrementing Double value. But for decrmenting double, there is no API.  Any possible way i can achieve this ? 

 Regards
Sridhar

**Comment by ipapapa** [comment]
Can you point me to the Redis command you are looking into getting implemented? I do not see `decrByFloat` in https://redis.io/commands

**Comment by duraisridhar** [comment]
Hi ,

Thanks for your clarification. . Closing this issue.
