### ISSUE TITLE
Use getMaxTimeoutWhenExhausted() when borrowing connection from pool

### ISSUE THREAD

**Issue by cporter71** [Netflix/dyno#51]
Should getMaxTimeoutWhenExhausted() should be used versus the connection timeout when selectionStrategy.getConnection().  This seems to be true for all use cases w/in ConnectionPoolImpl.java with exception to: getConnectionForOperation().

```
public <R> Connection<CL> getConnectionForOperation(BaseOperation<CL, R> baseOperation) {
- return selectionStrategy.getConnection(baseOperation, cpConfiguration.getConnectTimeout(), TimeUnit.MILLISECONDS);
+ return selectionStrategy.getConnection(baseOperation, cpConfiguration.getMaxTimeoutWhenExhausted(), TimeUnit.MILLISECONDS);	
```

**Comment by jcacciatore** [comment]
Fixed in [PR #121](https://github.com/Netflix/dyno/pull/121)
