### ISSUE TITLE
latest version (1.0.6) not in maven central

### ISSUE THREAD

**Issue by gadams00** [Netflix/dyno#57]
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22dyno-jedis%22

It looks as though the last version of dyno pushed to maven central is 1.0.4 on 11/3/2014. Are there plans to update this?

**Comment by opuneet** [comment]
@gadams00 we are actively working on Dyno. I just pushed a few fixes to it lately. You can see the commit history here. 
https://github.com/Netflix/dyno/commits/master

I'll check if the build for it was stuck somewhere in our build pipeline. Closing this out. Thanks.
