### ISSUE TITLE
Consider adding support for Buck build?

### ISSUE THREAD

**Issue by tfarina** [Netflix/dyno#73]
It would be interesting to be possible to build this with github.com/facebook/buck.

What do you think?

**Comment by jcacciatore** [comment]
I'm not familiar with Buck, but at a glance it seems targeted for Android apps, the big win being faster incremental builds. It may be interesting an interesting exercise but I don't see the value add. Unless I am missing something ?

**Comment by tfarina** [comment]
You can build pure Java applications too.

http://gerrit-talks.commondatastorage.googleapis.com/buck-rant.html#1

**Comment by jcacciatore** [comment]
Yes, compared to Ant and Maven I can see the value add but compared to gradle ? Can you describe the use case or scenario where this would be useful ?

**Comment by jcacciatore** [comment]
Closing this out for lack of response. @tfarina - feel free to re-open this if you want to pick up the discussion.

**Comment by tfarina** [comment]
https://www.pgrs.net/2015/09/01/migrating-from-gradle-to-bazel/
